version = 0.1
[default.deploy.parameters]
stack_name = "hashstream-consumer-node"
resolve_s3 = true
s3_prefix = "hashstream-consumer-node"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[prod-testnet.deploy.parameters]
stack_name = "hashstream-consumer-node"
resolve_s3 = true
s3_prefix = "hashstream-consumer-node"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "JwksUrl=\"https://testnet.streams-api.hashstream.xyz/webhook-keys\""
image_repositories = []

[prod-testnet.global.parameters]
region = "us-east-1"
